
class TaskError(Exception):
  """Raised to indicate a task has failed."""
